'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

sum all even numbers in this series below four million

Generate a fibbonacci number



'''

n  = 1
m  = 0
mm = 0
temp = 0
while n < 4000000:
    if n%2 == 0:
        temp += n
    mm = n # save n
    n = m + n
    m = mm
print(temp)
    
